Website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Account, COUNTRY_CURRENCY
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


from string import punctuation
from datetime import datetime
import re


def CheckCapital(string):
    for char in string:
        if char.isupper():
            return True
    return False

def CheckSpecialChar(string):
    special_characters = set(punctuation)  # Get all punctuation characters
    for char in string:
        if char in special_characters:
            return True
    return False

def CheckEmail(email):
    # Regular expression for validating email addresses
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    return re.match(pattern, email) is not None

def CheckDOB(DOB):
    try:
        datetime.strptime(DOB, '%d/%m/%Y')
        return True
    except ValueError:
        return False

def CheckAge(DOB):
    today = datetime.today()
    dob = datetime.strptime(DOB, '%d/%m/%Y')
    return today.year - dob.year

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.dashboard'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Username does not exist.', category='error')
    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':

        username = request.form.get('username')
        password = request.form.get('password')
        password1 = request.form.get('password1')
        email = request.form.get('email')
        address = request.form.get('address')
        country = request.form.get('country')
        dob = request.form.get('DOB')

        user = User.query.filter_by(username=username).first()
        user_country = COUNTRY_CURRENCY.query.filter_by(country=country).first()

        if user:
            flash('Username already exists!', category='error')
        elif not user_country:
            flash('App is not supported in your country', category='error')
        elif len(password) < 8:
            flash('Password must have atleast 8 characters', category='error')
        elif not CheckCapital(password):
            flash('Password must have an upper case character', category='error')
        elif not CheckSpecialChar(password):
            flash('Password must contain a special character', category='error')
        elif password != password1:
            flash('Passwords do not match', category='error')
        elif not CheckEmail(email):
            flash('Invalid email', category='error')
        elif not CheckDOB(dob):
            flash('Date of Birth must written as dd/mm/YYYY', category='error')
        elif CheckAge(dob) < 18:
            flash('You must be over 18 to register', category='error')
        else:
            new_user = User(
                username=username, 
                password=generate_password_hash(
                    password), 
                email=email, 
                address=address, 
                country=country, 
                dob=dob)
            
            db.session.add(new_user)
            db.session.commit()

            new_account = Account(
                user_id = new_user.id)
            
            db.session.add(new_account)
            db.session.commit()

            login_user(new_user, remember=True)
            flash('Account created successfully!', category='success')

            return redirect(url_for('views.dashboard'))
            
        
            

    return render_template('register.html', user=current_user)

Website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, send_from_directory
from flask_login import login_required, current_user
from .models import Account, User, COUNTRY_CURRENCY
from . import db
import os
from .currencybeacon import CurrencyExchanger

views = Blueprint('views', __name__)

@views.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(views.root_path, 'static'), 'favicon.ico', mimetype='image/vnd.microsoft.icon')

@views.route('/', methods=['GET', 'POST'])
@login_required
def dashboard():
    user = current_user
    accounts = Account.query.filter_by(user_id=user.id).first()
    balance = accounts.balance if accounts else None
    user_country = COUNTRY_CURRENCY.query.filter_by(country=user.country).first()
    symbol = user_country.currency_symbol

    return render_template('dashboard.html', user=current_user, accounts=accounts, balance=balance, symbol=symbol)


@views.route('/add_money', methods=['POST'])
def add_money():
    # Check if the user is logged in
    if not current_user.is_authenticated:
        return redirect(url_for('login'))
    
    # Get the amount to add from the form data
    amount = float(request.form['amount'])

    # Perform the addition to the user's account balance
    user_id = current_user.id
    account = Account.query.filter_by(user_id=user_id).first()
    if account:
        account.balance += amount
        db.session.commit()
        flash(f'Added {amount} to your account.', 'success')
    else:
        flash('Account not found.', 'error')

    return redirect(url_for('views.dashboard'))

@views.route('/withdraw_money', methods=['POST'])
def withdraw_money():
    # Check if the user is logged in
    if not current_user.is_authenticated:
        return redirect(url_for('login'))
    
    # Get the amount to withdraw from the form data
    amount = float(request.form['amount'])

    # Perform the withdrawal from the user's account balance
    user_id = current_user.id
    account = Account.query.filter_by(user_id=user_id).first()
    if account:
        if account.balance >= amount:
            account.balance -= amount
            db.session.commit()
            flash(f'Withdrawn {amount} from your account.', 'success')
        else:
            flash('Insufficient balance.', 'error')
    else:
        flash('Account not found.', 'error')

    return redirect(url_for('views.dashboard'))

@views.route('/transfer_money', methods=['POST'])
def transfer_money():
    # Check if the user is logged in
    if not current_user.is_authenticated:
        return redirect(url_for('login'))
    
    # Get transfer details from the form data
    recipient_username = request.form['recipient_username']
    amount = float(request.form['amount'])

    # Find sender's and recipient's accounts
    sender_id = current_user.id

    if recipient_username != current_user.username:
        sender_account = Account.query.filter_by(user_id=sender_id).first()
        recipient = User.query.filter_by(username=recipient_username).first()

        sender_country = COUNTRY_CURRENCY.query.filter_by(country=current_user.country).first()
        sender_currency = sender_country.currency_code

        if recipient:
            recipient_account = Account.query.filter_by(user_id=recipient.id).first()
            recipient_country = COUNTRY_CURRENCY.query.filter_by(country=recipient.country).first()
            recipient_currency = recipient_country.currency_code
        else:
            flash('Recipient not found.', 'error')
            return redirect(url_for('views.dashboard'))

        # Perform the transfer
        if sender_account and recipient_account:
            if sender_account.balance >= amount:
                currency_exchanger = CurrencyExchanger(sender_currency, recipient_currency, amount)

                response = currency_exchanger.api_call()
                if response.status_code == 200:
                    recipient_amount = currency_exchanger.get_value(response=response)

                    sender_account.balance -= amount
                    recipient_account.balance += round(recipient_amount, 2)
                    db.session.commit()
                    flash(f'Transferred {amount} to {recipient_username}.', category='success')
                else:
                    flash('Something went wrong 🤔', category='error')
            else:
                flash('Insufficient balance.', category='error')
        else:
            flash('Account not found.', category='error')
    else:
        flash('You cannot be recipient', category='error')
    return redirect(url_for('views.dashboard'))

Website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}dashboard{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">dashboard</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/register">Register</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    {% block javascript %}
    <script>
        function validateRegistrationForm() {
            var username = document.getElementById('username').value;
            var password = document.getElementById('password').value;
            
            if (username === '' || password === '') {
                alert('Please fill in all fields');
                return false;
            }
            return true;
        }
    
        function validateLoginForm() {
            var username = document.getElementById('username').value;
            var password = document.getElementById('password').value;
            
            if (username === '' || password === '') {
                alert('Please fill in all fields');
                return false;
            }
            return true;
        }
    </script>
    {% endblock %}
  </body>
</html>

Website/templates/dashboard.html
{% extends "base.html" %} {% block title %}dashboard{% endblock %} {% block content %}
<h1 align="center">Welcome, {{ user.username }}</h1>
<h3 align="center">Your Balance: {{ symbol }}{{ balance }}</h3>

<h2 align="center">Actions</h2>

<div class="form-group">
    <form action="{{ url_for('views.add_money') }}" method="post">
        <label for="amount">Amount to add:</label>
        <input type="number" step="0.01" id="amount" name="amount" required><br><br>
        <button type="submit">Add Money</button>
    </form>
</div>
  
<div class="form-group">
    <form action="{{ url_for('views.withdraw_money') }}" method="post">
        <label for="amount">Amount to withdraw:</label>
        <input type="number" step="0.01" id="amount" name="amount" required><br><br>
        <button type="submit">Withdraw Money</button>
    </form>
</div>

<div class="form-group">
    <form action="{{ url_for('views.transfer_money') }}" method="post">
        <label for="amount">Amount to transfer:</label>
        <input type="number" step="0.01" id="amount" name="amount" required><br><br>
        <label for="recipient_username">Receiver Username:</label>
        <input type="text" id="recipient_username" name="recipient_username" required><br><br>
        <button type="submit">Transfer Money</button>
    </form>
</div>
{% endblock %}

Website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <h2>Login</h2>
    {% if error %}
        <p style="color: red;">{{ error }}</p>
    {% endif %}
    <form method="post">
        <label for="username">Username:</label><br>
        <input type="text" id="username" name="username"><br>
        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password"><br><br>
        <input type="submit" value="Login">
    </form>
{% endblock %}

Website/templates/register.html
{% extends "base.html" %} {% block title %}Register{% endblock %} {% block
    content %}
    <h1>Register</h1>
    <form action="{{ url_for('auth.register') }}" method="post">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required><br><br>
        <label for="email">Email:</label>
        <input type="text" id="email" name="email" required><br><br>
        <label for="address">Address:</label>
        <input type="text" id="address" name="address" required><br><br>
        <label for="country">Country of residance:</label>
        <input type="text" id="country" name="country" required><br><br>
        <label for="DOB">Date of Birth:</label>
        <input type="text" id="DOB" name="DOB" required><br><br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required><br><br>
        <label for="password1">Confirm Password:</label>
        <input type="password" id="password1" name="password1" required><br><br>
        <button type="submit">Register</button>
    </form>
</body>
</html>
{% endblock %}